### ISSUE TITLE
Remove the import lowercase, and use lower directly as a method of a string

### ISSUE THREAD

**Issue by emres** [ErwinBaeyens/python-lander#2]
On [line 58](https://github.com/ErwinBaeyens/python-lander/blob/master/lander.py#L58), you can use `str(raw_input()).lower()` instead of `lower(str(raw_input()))`, so that you can also get rid of the import on [line 3](https://github.com/ErwinBaeyens/python-lander/blob/master/lander.py#L3)

**Comment by ErwinBaeyens** [comment]
easy fix to get more pythonic ;-)
