### ISSUE TITLE
Create a main entry point and better project structure

### ISSUE THREAD

**Issue by emres** [ErwinBaeyens/python-lander#3]
Create a main entry point and better project structure

See the following:

* https://docs.python.org/2.7/library/__main__.html
* http://docs.python-guide.org/en/latest/writing/structure/
* http://stackoverflow.com/questions/193161/what-is-the-best-project-structure-for-a-python-application

**Comment by ErwinBaeyens** [comment]
restructured the source in 2 files 
lander.py  containing the class Lander
and main.py  being the main program
